### ISSUE TITLE
updating

### ISSUE THREAD

**Issue by remotevase** [opum2/opum2.github.io#1]
Really needs a ton of updating... Either Google since templates or figure out how to make it look less basic... I didn't use a template that I got from Google, yet my website looks awesome! See it at https://remotevase.github.io

**Comment by opum2** [comment]
This is a template. Do you know how much I changed? So much, lol. I actually made it so that some pages don't have a side column, I changed all the colors, I changed the logo up top, and all that. Gonna try out a few different templates under different branches. ;)

**Comment by remotevase** [comment]
good, you definitely need to,--no offence...
